# Generated by Django 4.2.13 on 2026-05-08 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrimonialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('family_type', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='matrimonial/')),
                ('bio', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matrimonial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
