# Generated by Django 4.2.13 on 2026-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.CharField(default='Welcome to Sahu Sabha', max_length=255)),
                ('hero_subtext', models.TextField(default='Empowering our community')),
                ('contact_email', models.EmailField(default='contact@sahusabha.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91 00000 00000', max_length=20)),
                ('about_text', models.TextField(default='About Sahu Sabha')),
            ],
        ),
    ]
